"""baseline

Revision ID: 20260318_0001
Revises: 
Create Date: 2026-03-18 22:28:37.250993
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '20260318_0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('ref_table', sa.String(length=50), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('layer', sa.String(length=30), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_items_layer'), 'memory_items', ['layer'], unique=False)
    op.create_index(op.f('ix_memory_items_memory_type'), 'memory_items', ['memory_type'], unique=False)
    op.create_index(op.f('ix_memory_items_ref_id'), 'memory_items', ['ref_id'], unique=False)
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.Text(), nullable=False),
    sa.Column('abstract_en', sa.Text(), nullable=False),
    sa.Column('authors', sa.Text(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=False),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('pdf_local_path', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_paper_source_sourceid')
    )
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_index(op.f('ix_papers_source'), 'papers', ['source'], unique=False)
    op.create_index(op.f('ix_papers_source_id'), 'papers', ['source_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interests', sa.Text(), nullable=False),
    sa.Column('preferred_methods', sa.Text(), nullable=False),
    sa.Column('focus_topics', sa.Text(), nullable=False),
    sa.Column('research_goal', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('research_question', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('seed_query', sa.Text(), nullable=False),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_projects_status'), 'research_projects', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('trigger_source', sa.String(length=20), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_table('translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('locator_json', sa.Text(), nullable=False),
    sa.Column('content_en_snapshot', sa.Text(), nullable=False),
    sa.Column('content_zh', sa.Text(), nullable=False),
    sa.Column('disclaimer', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_type', 'target_id', 'unit_type', 'field_name', 'locator_json', name='uq_translation_target_unit')
    )
    op.create_index(op.f('ix_translations_target_id'), 'translations', ['target_id'], unique=False)
    op.create_index(op.f('ix_translations_target_type'), 'translations', ['target_type'], unique=False)
    op.create_index(op.f('ix_translations_unit_type'), 'translations', ['unit_type'], unique=False)
    op.create_table('ideas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('idea_type', sa.String(length=30), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_idea_type'), 'ideas', ['idea_type'], unique=False)
    op.create_index(op.f('ix_ideas_paper_id'), 'ideas', ['paper_id'], unique=False)
    op.create_table('memory_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_memory_id', sa.Integer(), nullable=False),
    sa.Column('to_memory_id', sa.Integer(), nullable=False),
    sa.Column('link_type', sa.String(length=30), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['from_memory_id'], ['memory_items.id'], ),
    sa.ForeignKeyConstraint(['to_memory_id'], ['memory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memory_links_from_memory_id'), 'memory_links', ['from_memory_id'], unique=False)
    op.create_index(op.f('ix_memory_links_to_memory_id'), 'memory_links', ['to_memory_id'], unique=False)
    op.create_table('paper_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_annotations_paper_id'), 'paper_annotations', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_annotations_paragraph_id'), 'paper_annotations', ['paragraph_id'], unique=False)
    op.create_table('paper_research_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('reading_status', sa.String(length=20), nullable=False),
    sa.Column('interest_level', sa.Integer(), nullable=False),
    sa.Column('repro_interest', sa.String(length=20), nullable=False),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('topic_cluster', sa.String(length=255), nullable=False),
    sa.Column('is_core_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_research_state_is_core_paper'), 'paper_research_state', ['is_core_paper'], unique=False)
    op.create_index(op.f('ix_paper_research_state_paper_id'), 'paper_research_state', ['paper_id'], unique=True)
    op.create_index(op.f('ix_paper_research_state_reading_status'), 'paper_research_state', ['reading_status'], unique=False)
    op.create_table('repos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('repo_url', sa.Text(), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('forks', sa.Integer(), nullable=False),
    sa.Column('readme_summary', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repos_paper_id'), 'repos', ['paper_id'], unique=False)
    op.create_table('research_project_outputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('output_type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content_json', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_project_outputs_output_type'), 'research_project_outputs', ['output_type'], unique=False)
    op.create_index(op.f('ix_research_project_outputs_project_id'), 'research_project_outputs', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_project_outputs_status'), 'research_project_outputs', ['status'], unique=False)
    op.create_table('research_project_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'paper_id', name='uq_research_project_paper')
    )
    op.create_index(op.f('ix_research_project_papers_paper_id'), 'research_project_papers', ['paper_id'], unique=False)
    op.create_index(op.f('ix_research_project_papers_project_id'), 'research_project_papers', ['project_id'], unique=False)
    op.create_table('summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('summary_type', sa.String(length=20), nullable=False),
    sa.Column('content_en', sa.Text(), nullable=False),
    sa.Column('problem_en', sa.Text(), nullable=False),
    sa.Column('method_en', sa.Text(), nullable=False),
    sa.Column('contributions_en', sa.Text(), nullable=False),
    sa.Column('limitations_en', sa.Text(), nullable=False),
    sa.Column('future_work_en', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_paper_id'), 'summaries', ['paper_id'], unique=False)
    op.create_index(op.f('ix_summaries_summary_type'), 'summaries', ['summary_type'], unique=False)
    op.create_table('task_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_ref_type', sa.String(length=50), nullable=False),
    sa.Column('artifact_ref_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_artifacts_artifact_type'), 'task_artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_task_artifacts_task_id'), 'task_artifacts', ['task_id'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('week_end', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('draft_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_snapshot_json', sa.Text(), nullable=False),
    sa.Column('generated_task_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['generated_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_reports_generated_task_id'), 'weekly_reports', ['generated_task_id'], unique=False)
    op.create_index(op.f('ix_weekly_reports_status'), 'weekly_reports', ['status'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_end'), 'weekly_reports', ['week_end'], unique=False)
    op.create_index(op.f('ix_weekly_reports_week_start'), 'weekly_reports', ['week_start'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_paper_id'), 'notes', ['paper_id'], unique=False)
    op.create_index(op.f('ix_notes_summary_id'), 'notes', ['summary_id'], unique=False)
    op.create_table('reproductions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('repo_id', sa.Integer(), nullable=True),
    sa.Column('plan_markdown', sa.Text(), nullable=False),
    sa.Column('progress_summary', sa.Text(), nullable=False),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reproductions_paper_id'), 'reproductions', ['paper_id'], unique=False)
    op.create_index(op.f('ix_reproductions_repo_id'), 'reproductions', ['repo_id'], unique=False)
    op.create_index(op.f('ix_reproductions_status'), 'reproductions', ['status'], unique=False)
    op.create_table('research_project_evidence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=True),
    sa.Column('summary_id', sa.Integer(), nullable=True),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('source_label', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['research_projects.id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_project_evidence_items_kind'), 'research_project_evidence_items', ['kind'], unique=False)
    op.create_index(op.f('ix_research_project_evidence_items_paper_id'), 'research_project_evidence_items', ['paper_id'], unique=False)
    op.create_index(op.f('ix_research_project_evidence_items_project_id'), 'research_project_evidence_items', ['project_id'], unique=False)
    op.create_index(op.f('ix_research_project_evidence_items_summary_id'), 'research_project_evidence_items', ['summary_id'], unique=False)
    op.create_table('reflections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reflection_type', sa.String(length=30), nullable=False),
    sa.Column('related_paper_id', sa.Integer(), nullable=True),
    sa.Column('related_summary_id', sa.Integer(), nullable=True),
    sa.Column('related_repo_id', sa.Integer(), nullable=True),
    sa.Column('related_reproduction_id', sa.Integer(), nullable=True),
    sa.Column('related_task_id', sa.Integer(), nullable=True),
    sa.Column('template_type', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=30), nullable=False),
    sa.Column('lifecycle_status', sa.String(length=20), nullable=False),
    sa.Column('content_structured_json', sa.Text(), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('is_report_worthy', sa.Boolean(), nullable=False),
    sa.Column('report_summary', sa.Text(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['related_paper_id'], ['papers.id'], ),
    sa.ForeignKeyConstraint(['related_repo_id'], ['repos.id'], ),
    sa.ForeignKeyConstraint(['related_reproduction_id'], ['reproductions.id'], ),
    sa.ForeignKeyConstraint(['related_summary_id'], ['summaries.id'], ),
    sa.ForeignKeyConstraint(['related_task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reflections_event_date'), 'reflections', ['event_date'], unique=False)
    op.create_index(op.f('ix_reflections_lifecycle_status'), 'reflections', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_reflections_reflection_type'), 'reflections', ['reflection_type'], unique=False)
    op.create_index(op.f('ix_reflections_related_paper_id'), 'reflections', ['related_paper_id'], unique=False)
    op.create_index(op.f('ix_reflections_related_repo_id'), 'reflections', ['related_repo_id'], unique=False)
    op.create_index(op.f('ix_reflections_related_reproduction_id'), 'reflections', ['related_reproduction_id'], unique=False)
    op.create_index(op.f('ix_reflections_related_summary_id'), 'reflections', ['related_summary_id'], unique=False)
    op.create_index(op.f('ix_reflections_related_task_id'), 'reflections', ['related_task_id'], unique=False)
    op.create_table('reproduction_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reproduction_id', sa.Integer(), nullable=False),
    sa.Column('step_no', sa.Integer(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('step_status', sa.String(length=20), nullable=False),
    sa.Column('progress_note', sa.Text(), nullable=False),
    sa.Column('blocker_reason', sa.Text(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requires_manual_confirm', sa.Boolean(), nullable=False),
    sa.Column('expected_output', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reproduction_id'], ['reproductions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reproduction_steps_reproduction_id'), 'reproduction_steps', ['reproduction_id'], unique=False)
    op.create_index(op.f('ix_reproduction_steps_step_status'), 'reproduction_steps', ['step_status'], unique=False)
    op.create_table('reproduction_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reproduction_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('log_text', sa.Text(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('next_step_suggestion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reproduction_id'], ['reproductions.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['reproduction_steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reproduction_logs_reproduction_id'), 'reproduction_logs', ['reproduction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reproduction_logs_reproduction_id'), table_name='reproduction_logs')
    op.drop_table('reproduction_logs')
    op.drop_index(op.f('ix_reproduction_steps_step_status'), table_name='reproduction_steps')
    op.drop_index(op.f('ix_reproduction_steps_reproduction_id'), table_name='reproduction_steps')
    op.drop_table('reproduction_steps')
    op.drop_index(op.f('ix_reflections_related_task_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_related_summary_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_related_reproduction_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_related_repo_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_related_paper_id'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_reflection_type'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_lifecycle_status'), table_name='reflections')
    op.drop_index(op.f('ix_reflections_event_date'), table_name='reflections')
    op.drop_table('reflections')
    op.drop_index(op.f('ix_research_project_evidence_items_summary_id'), table_name='research_project_evidence_items')
    op.drop_index(op.f('ix_research_project_evidence_items_project_id'), table_name='research_project_evidence_items')
    op.drop_index(op.f('ix_research_project_evidence_items_paper_id'), table_name='research_project_evidence_items')
    op.drop_index(op.f('ix_research_project_evidence_items_kind'), table_name='research_project_evidence_items')
    op.drop_table('research_project_evidence_items')
    op.drop_index(op.f('ix_reproductions_status'), table_name='reproductions')
    op.drop_index(op.f('ix_reproductions_repo_id'), table_name='reproductions')
    op.drop_index(op.f('ix_reproductions_paper_id'), table_name='reproductions')
    op.drop_table('reproductions')
    op.drop_index(op.f('ix_notes_summary_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_paper_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_weekly_reports_week_start'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_week_end'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_status'), table_name='weekly_reports')
    op.drop_index(op.f('ix_weekly_reports_generated_task_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_task_artifacts_task_id'), table_name='task_artifacts')
    op.drop_index(op.f('ix_task_artifacts_artifact_type'), table_name='task_artifacts')
    op.drop_table('task_artifacts')
    op.drop_index(op.f('ix_summaries_summary_type'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_paper_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_research_project_papers_project_id'), table_name='research_project_papers')
    op.drop_index(op.f('ix_research_project_papers_paper_id'), table_name='research_project_papers')
    op.drop_table('research_project_papers')
    op.drop_index(op.f('ix_research_project_outputs_status'), table_name='research_project_outputs')
    op.drop_index(op.f('ix_research_project_outputs_project_id'), table_name='research_project_outputs')
    op.drop_index(op.f('ix_research_project_outputs_output_type'), table_name='research_project_outputs')
    op.drop_table('research_project_outputs')
    op.drop_index(op.f('ix_repos_paper_id'), table_name='repos')
    op.drop_table('repos')
    op.drop_index(op.f('ix_paper_research_state_reading_status'), table_name='paper_research_state')
    op.drop_index(op.f('ix_paper_research_state_paper_id'), table_name='paper_research_state')
    op.drop_index(op.f('ix_paper_research_state_is_core_paper'), table_name='paper_research_state')
    op.drop_table('paper_research_state')
    op.drop_index(op.f('ix_paper_annotations_paragraph_id'), table_name='paper_annotations')
    op.drop_index(op.f('ix_paper_annotations_paper_id'), table_name='paper_annotations')
    op.drop_table('paper_annotations')
    op.drop_index(op.f('ix_memory_links_to_memory_id'), table_name='memory_links')
    op.drop_index(op.f('ix_memory_links_from_memory_id'), table_name='memory_links')
    op.drop_table('memory_links')
    op.drop_index(op.f('ix_ideas_paper_id'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_idea_type'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_translations_unit_type'), table_name='translations')
    op.drop_index(op.f('ix_translations_target_type'), table_name='translations')
    op.drop_index(op.f('ix_translations_target_id'), table_name='translations')
    op.drop_table('translations')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_research_projects_status'), table_name='research_projects')
    op.drop_table('research_projects')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_papers_source_id'), table_name='papers')
    op.drop_index(op.f('ix_papers_source'), table_name='papers')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_memory_items_ref_id'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_memory_type'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_layer'), table_name='memory_items')
    op.drop_table('memory_items')
    # ### end Alembic commands ###
